site:
  title: GeoGebra Manual
  start_page: manual::index.adoc
content:
  sources:
    - url: https://github.com/geogebra/manual
      start_paths:
        - en
        - it
ui:
  bundle:
    url: ./ui-bundle
    snapshot: true